name: Build and Run

on: [push, pull_request]

env:
  DOTNET_VERSION: '6.0.401'

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
        # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}      
      - name: tshirts
        run: |
          cd tshirts
          bash ../.github/workflows/expectfail.sh dotnet run
      - name: misaligned
        run: |
          cd misaligned
          bash ../.github/workflows/expectfail.sh dotnet run
      - name: weather-report
        run: |
          cd weatherreport
          bash ../.github/workflows/expectfail.sh dotnet run
