name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Fail on false positive
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
      - run: |
          cd alerter
          dotnet run
